-- 0. (중요) 기존 테이블이 있다면 먼저 확인 필요하나, 에러가 발생했으므로 새로 생성합니다.
create table if not exists "ProjectRating" (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  project_id bigint not null, -- Project 테이블의 id 참조 (FK는 선택사항)
  user_id uuid, -- 로그인 유저 (Nullable)
  guest_id text, -- 게스트 식별자 (Nullable)
  score float default 0, -- 평균 점수
  score_1 float default 0,
  score_2 float default 0,
  score_3 float default 0,
  score_4 float default 0,
  score_5 float default 0,
  score_6 float default 0,
  proposal text, -- 종합 의견
  custom_answers jsonb default '{}'::jsonb, -- 주관식 답변용
  vote_type text -- 스티커 투표 (선택적)
);

-- 1. 중복 평가 방지를 위한 유니크 인덱스
-- 로그인 유저용
create unique index if not exists idx_rating_user 
on "ProjectRating" (project_id, user_id) 
where user_id is not null;

-- 게스트 유저용
create unique index if not exists idx_rating_guest 
on "ProjectRating" (project_id, guest_id) 
where guest_id is not null;

-- 2. RLS 설정 (API 서버만 접근 허용 권장)
alter table "ProjectRating" enable row level security;

create policy "Enable access for service role"
  on "ProjectRating"
  for all
  to service_role
  using (true)
  with check (true);

-- (옵션) 클라이언트에서 직접 조회를 위해 public read 허용
create policy "Enable read for all"
  on "ProjectRating"
  for select
  using (true);
