-- 1. Create ProjectPoll table if it doesn't exist
create table if not exists "ProjectPoll" (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  project_id bigint not null, -- References Project(project_id)
  user_id uuid, -- Nullable for guests
  guest_id text, -- Nullable for logged-in users
  vote_type text not null -- 'launch', 'research', 'more' etc.
);

-- 2. Add guest_id column if table existed but column didn't (Safe check)
alter table "ProjectPoll" add column if not exists guest_id text;

-- 3. Indexes for uniqueness
-- Drop existing constraints if they exist to avoid conflicts/errors on re-run
drop index if exists idx_poll_user;
drop index if exists idx_poll_guest;
-- Also drop potential unique constraints from previous schema versions
alter table "ProjectPoll" drop constraint if exists "ProjectPoll_project_id_user_id_key";

-- Create partial unique index for Logged-in Users
create unique index idx_poll_user 
on "ProjectPoll" (project_id, user_id) 
where user_id is not null;

-- Create partial unique index for Guests
create unique index idx_poll_guest 
on "ProjectPoll" (project_id, guest_id) 
where guest_id is not null;

-- 4. RLS Policies
alter table "ProjectPoll" enable row level security;

-- Allow public read (anyone can see vote counts)
create policy "Enable read for all"
  on "ProjectPoll"
  for select
  using (true);

-- Allow service role full access (API handles auth/identification logic)
create policy "Enable access for service role"
  on "ProjectPoll"
  for all
  to service_role
  using (true)
  with check (true);
