-- [CRITICAL] MyRatingIs Database Recovery Script
-- 이 스크립트는 누락된 테이블을 복구하고 제약 조건을 수리하여 제출 오류를 해결합니다.
-- Supabase SQL Editor에서 실행하세요.

-- 1. ProjectRating 테이블 확인 및 복구
create table if not exists public."ProjectRating" (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  project_id bigint not null,
  user_id uuid references auth.users(id) on delete cascade,
  guest_id text,
  score float default 0,
  score_1 float default 0,
  score_2 float default 0,
  score_3 float default 0,
  score_4 float default 0,
  score_5 float default 0,
  score_6 float default 0,
  proposal text,
  custom_answers jsonb default '{}'::jsonb,
  vote_type text
);

-- 유니크 인덱스 (로그인 유저/게스트 중복 방지)
do $$ begin
  create unique index idx_rating_user on public."ProjectRating" (project_id, user_id) where user_id is not null;
exception when others then null; end $$;

do $$ begin
  create unique index idx_rating_guest on public."ProjectRating" (project_id, guest_id) where guest_id is not null;
exception when others then null; end $$;

-- 2. ProjectPoll (스티커 투표) 테이블 복구
create table if not exists public."ProjectPoll" (
  id bigint generated by default as identity primary key,
  project_id bigint not null,
  user_id uuid references auth.users(id) on delete cascade,
  guest_id text,
  vote_type text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

do $$ begin
  create unique index idx_poll_user on public."ProjectPoll" (project_id, user_id) where user_id is not null;
exception when others then null; end $$;

do $$ begin
  create unique index idx_poll_guest on public."ProjectPoll" (project_id, guest_id) where guest_id is not null;
exception when others then null; end $$;

-- 3. notifications 테이블 수리 (FK 제약 조건 유연화)
-- 만약 profiles 테이블이 없거나 프로젝트 소유자가 users에만 있는 경우를 대비하여 references 제거
alter table if exists public.notifications drop constraint if exists notifications_user_id_fkey;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  type text not null,
  title text not null,
  message text,
  link text,
  read boolean default false,
  sender_id uuid,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS 활성화
alter table public."ProjectRating" enable row level security;
alter table public."ProjectPoll" enable row level security;
alter table public.notifications enable row level security;

-- 누구나 다 볼 수 있고, 서비스 롤(API)은 모든 권한 수행 가능 정책
do $$ begin
  create policy "Public Select" on public."ProjectRating" for select using (true);
  create policy "Public Select" on public."ProjectPoll" for select using (true);
  create policy "System All" on public."ProjectRating" for all to service_role using (true);
  create policy "System All" on public."ProjectPoll" for all to service_role using (true);
  create policy "System All" on public.notifications for all to service_role using (true);
exception when others then null; end $$;

-- 4. Project 읽기 권한 확인
drop policy if exists "Enable read access for all users" on "Project";
create policy "Enable read access for all users" on "Project" for select using (true);
