-- [MyRatingIs] Notifications Table & Backfill
-- Run this SQL in Supabase SQL Editor

-- 1. Create Notifications Table (if missing)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  type text not null, -- 'point', 'system', 'audit', etc.
  title text not null,
  message text,
  link text,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Notifications
alter table public.notifications enable row level security;
create policy "Users can view their own notifications." on public.notifications for select using (auth.uid() = user_id);
create policy "Users can update their own notifications." on public.notifications for update using (auth.uid() = user_id);

-- 2. Backfill Profiles for existing Users (Robust Fix)
-- auth.users에는 있지만 public.profiles에는 없는 유저들을 찾아 프로필을 생성합니다.
do $$
declare
  missing_user record;
begin
  for missing_user in 
    select id, email, raw_user_meta_data 
    from auth.users 
    where id not in (select id from public.profiles)
  loop
    insert into public.profiles (id, username, email, avatar_url, points)
    values (
      missing_user.id,
      coalesce(missing_user.raw_user_meta_data->>'full_name', split_part(missing_user.email, '@', 1)),
      missing_user.email,
      coalesce(missing_user.raw_user_meta_data->>'avatar_url', '/globe.svg'),
      1000
    )
    on conflict (id) do nothing;
  end loop;
end;
$$;
