-- [MyRatingIs] Database Initialization SQL
-- Supabase SQL Editor에서 이 스크립트를 실행하여 필수 테이블을 생성해주세요.

-- 1. UUID Extension
create extension if not exists "uuid-ossp";

-- 2. Profiles Table (사용자 프로필)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  nickname text,
  avatar_url text,
  profile_image_url text,
  email text,
  points integer default 1000,
  expertise jsonb default '{}'::jsonb,
  interests jsonb default '{}'::jsonb,
  onboarding_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

-- 3. Project Table (프로젝트/진단 의뢰)
create table if not exists public."Project" (
  project_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  category_id bigint default 1,
  title text not null,
  summary text,
  content_text text,
  description text,
  thumbnail_url text,
  rendering_type text default 'rich_text',
  custom_data jsonb default '{}'::jsonb,
  views_count integer default 0,
  likes_count integer default 0,
  is_growth_requested boolean default false,
  allow_michelin_rating boolean default true,
  allow_stickers boolean default true,
  allow_secret_comments boolean default true,
  visibility text default 'public',
  audit_deadline timestamp with time zone,
  scheduled_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  deleted_at timestamp with time zone
);

-- RLS for Project
alter table public."Project" enable row level security;
create policy "Projects are viewable by everyone." on public."Project" for select using (true);
create policy "Users can insert their own project." on public."Project" for insert with check (auth.uid() = user_id);
create policy "Users can update their own project." on public."Project" for update using (auth.uid() = user_id);

-- 4. Fields Table (분야 메타 데이터)
create table if not exists public.fields (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null
);

insert into public.fields (slug, name) values 
('it', 'IT/Tech'), 
('design', 'Design/Art'), 
('marketing', 'Marketing'), 
('business', 'Business'), 
('contents', 'Contents')
on conflict (slug) do nothing;

-- 5. Project Fields Mapping (프로젝트-분야 연결)
create table if not exists public.project_fields (
  project_id bigint references public."Project"(project_id) on delete cascade,
  field_id bigint references public.fields(id) on delete cascade,
  unique (project_id, field_id)
);

-- 6. Project Categories Mapping (추가 카테고리/장르)
create table if not exists public.project_categories (
  id bigint generated by default as identity primary key,
  project_id bigint references public."Project"(project_id) on delete cascade,
  category_id bigint,
  category_type text
);

-- 7. Point Logs (포인트 기록)
create table if not exists public.point_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  amount integer not null,
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Auto Profile Trigger (회원가입 시 프로필 자동생성 - 안전장치)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, email, avatar_url, points)
  values (
    new.id, 
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', '/globe.svg'),
    1000
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger check and create
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
